services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data


  app:
    build:
      context: .
    ports:
      - 8000:8000
    container_name: django-app
    command: >
      sh -c "python3 manage.py wait_for_db &&
      python manage.py migrate &&  
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/app

