services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./env/.env
    volumes:
      - postgres_data:/db:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static_volume:/var/www/web/static
      - media_volume:/var/www/web/media
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: app
    command: /start
    volumes:
      - .:/app
    env_file:
      - ./env/.env
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis:alpine
    container_name: redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./env/.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./env/.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./env/.env
    ports:
      - 57:5555
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
  static_volume:
  media_volume: