# Generated by Django 5.1.2 on 2024-10-31 15:50

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_is_active_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatar_docker.jpeg', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Image type must be like: jpg, png, jpeg'), core.models.image_size_validators]),
        ),
    ]
